# **Laboratorio 1: Una introducción a NumPy**

**Facultad de ingeniería**

Departamento de Ingeniería Biomédica

Universidad de los Andes

**IBIO-2340:** Fundamentos de Machine Learning

**Nombres de los integrantes**


1.   Nombre integrante 1
2.   Nombre integrante 2

**Número del grupo**

*Escribir el número del grupo*


# **1. Funciones en Python**

Para cada uno de los siguientes problemas, implemente una función que los resuelva. No puede utilizar ninguna librería externa de Python como NumPy o Scipy con métodos preestablecidos para resolverlos. Ponga a prueba cada función con el ejemplo que se proporciona.

**1.1.** Escriba una función que reciba como argumento una lista con números y retorne la suma de todos los números dentro de la misma.

In [1]:
# Complete la siguiente implementación
def sum_array(array):
    result = 0
    for element in array:
        result += element
    return result

In [2]:
# Ejemplo de prueba Ejercicio 1.1
a = [1,2,3,4,5]
sum_array(a)

15

**1.2.** Escriba una función que reciba como argumento un numero entero positivo y retorne el factorial del mismo.

**Nota:** Recuerde la definición del factorial de un número entero:

\begin{align}
        n! = n * (n-1) * (n-2) * (n-3) * ... *(1)
\end{align}

Y que, por definición, $0! = 1$.

In [ ]:
# Complete la siguiente implementación
def factorial_custom():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 1.2
factorial_custom(8)

**1.3.** Escriba una función que reciba como argumento una lista con números y retorne el promedio ponderado de los números dentro de la misma. Asuma que cada elemento tiene como peso su índice dentro de la lista, en este sentido el primer elemento tiene peso 0.

In [ ]:
# Complete la siguiente implementación
def weight_mean():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 1.3
b = [1,2,3,4,60]
weight_mean(b)

# **2. ¿Qué es NumPy?**

NumPy es una de las librerías más utilizadas en Python, permite operar matemáticamente grandes cantidades de datos almacenados en estructuras conocidas como *ndarrays*. Numpy es una librería inmensa que contiene diversos módulos orientados a campos específicos dentro de todos ellos nos interesan particularmente *np.linalg*  y *np.random*. 

El módulo *np.linalg* implementa distintas operaciones dentro del campo del álgebra lineal, que abarcan desde la artimética matricial básica, el cálculo de determinantes, inversas, autovalores y autovectores hasta complejas transformaciones para el procesamiento de señales.

Por su parte, el módulo *np.random* contiene implementaciones enfocadas en el análisis estadístico de datos. Permite calcular desde los estadísticos de orden hasta la generación de números aleatorios de acuerdo a diferentes distribuciones de probabilidad.

Por todo lo anterior, así como por su facilidad de implementación, es una librería de uso muy común en programación científica y un componente fundamental en el desarrollo de proyectos en Machine Learning. A continuación veremos con detalle algunas de sus funciones más importantes que nos serán de utilidad durante el desarrollo del curso.

**Operaciones Básicas con Arreglos**

Numpy posee varias funciones que son de utilidad operando arreglos. A continuación se detallan algunas:

- **np.sum:** Retorna la suma de todos los números contenidos en un arreglo.

- **np.prod:** Retorna la multiplicación de todos los números contenidos en un arreglo.

- **np.mean:** Retorna el promedio aritmético de todos los números contenidos en un arreglo.

- **np.average:** Retorna el promedio ponderado de todos los números contenidos en un arreglo.

- **np.std:** Retorna la desviación estandar de todos los números contenidos en un arreglo.


Así mismo Numpy implementa diferentes funciones matemáticas básicas que se aplican sobre arreglos (ver https://numpy.org/doc/stable/reference/routines.math.html). Dentro de los entornos de programación científica se considera buena práctica utilizar estas implementaciones en lugar de las nativas que se tienen en Python.

En primer lugar importamos Numpy. Al ser una librería externa es necesario instalarla previamente usando el manejador de paquetes de Python **pip**.

In [2]:
try:
  import numpy as np
  print(f"Numpy versión {np.__version__} se encuentra instalada en su sistema.")
except ImportError:
  print("Numpy no fue encontrado en su sistema. Verifique su instalación.")

Numpy versión 2.3.2 se encuentra instalada en su sistema.


**2.1.** A continuación, repita los puntos 1.1, 1.2 y 1.3 pero utilice las funciones y arreglos de Numpy para sus implementaciones. Recuerde revisar la documentación de la librería como ayuda.

In [ ]:
#Repetición punto 1.1
def sum_array_numpy():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 2.1
a = [1,2,3,4,5]
sum_1 = sum_array_numpy(a)
print(sum_1)

In [ ]:
#Repetición punto 1.2
def factorial_custom_numpy():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 2.1
prod_1 =  factorial_custom_numpy(8)
print(prod_1)

In [ ]:
#Repetición punto 1.3
def weight_mean_numpy():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 2.1
b = [1,2,3,4,60]
mean_1 = weight_mean_numpy(b)
print(mean_1)

# **3. Arrays en Numpy**

Los objetos fundamentales de Numpy son los *ndarrays* o simplemente **numpy arrays**, una estructura de datos similar a la lista tradicional de Python pero que ofrece mayor eficiencia en el almacenamiento y acceso a los datos y brinda una mayor versatilidad al realizar operaciones matemáticas. Los arrays son útiles para representar información como vectores y matrices.

Para iniciar un vector con los números de 1 a 5 se utiliza la instrucción 'np.array()' de la siguiente manera:

In [ ]:
vector = np.array([1,2,3,4,5])
print(vector)

De forma similar, una matriz puede ser iniciada como un arreglo de arreglos. Por ejemplo, para iniciar una matriz 2x2 que contenga los números de 1 a 4 se debe realizar lo siguiente:

In [ ]:
matriz = np.array([[1,2],[3,4]])
print(matriz)

Los ndarrays incluyen diferentes atributos que proporcionan información sobre el arreglo y permiten algunas operaciones básicas. Entre los más utilizados tenemos:

- **array.ndim:** Retorna la dimensión de un arreglo, entendida como el número de grados de libertad; 0 en el caso de un escalar, 1 en el caso de un vector, 2 en el caso de una matriz, ...

- **array.shape:** Retorna el tamaño de un arreglo, entendido como el número de elementos (si es un vector), filas y columnas (si es una matriz), ...

- **array.size:** Retorna el número total de elementos que contiene un arreglo.

- **array.T:** Retorna el arreglo transpuesto.

Algunos ejemplos de estos atributos se ven a continuación:

In [ ]:
print("Dimensión del arreglo:", matriz.ndim)
print("Tamaño del arreglo", matriz.shape)
print("Numero de elementos en el arreglo:", matriz.size)
print("Matriz transpuesta:\n", matriz.T)

**3.1. Indexación de arreglos de Numpy**


La indexación es una operación que permite obtener el elemento de una determinada posición dentro de un arreglo. Se utilizan los paréntesis cuadrados ([]) para indicar la posición de la que se quiere extraer el valor. En NumPy la indexación de los ndarrays es similar a la realizada sobre listas de Python.

Cuando se tiene un vector, cualquier posición puede ser obtenida simplemente indicando el nombre del vector y la posición deseada. La posición en el arreglo de cualquier elemento se especifica atraves de su índice, un número entero que va desde 0 hasta el número de elementos del arreglo. Tanto en Numpy como en Python, **el primer elemento tiene como índice a cero.** Por ejemplo, para obtener el tercer elemento del arreglo, pasamos su índice (2):

In [3]:
vector = np.array([1,2,3,4,5])
print(vector[2])

3


Por otra parte, el acceso a los elementos de una matriz se realiza con una doble indexación: [número de fila, número de columna]. **Se debe tener en cuenta que al igual que los arreglos unidimensionales, la indexación inicia en cero !!**. La primera fila de la matriz tiene índice cero, así como la primera columna. Por ejemplo, para obtener el elemento que se encuentra en la primera fila y la segunda columna escribimos:

In [6]:
matriz = np.array([[1,2],[3,4]])
print(matriz[0,1])
# Otra notación equivalente es:
print(matriz[0][1])

2
2


**3.2. Slicing en arreglos de Numpy**

Se conoce como *Slicing* a la operación que permite recuperar elementos específicos contenidos en un arreglo y agruparlos bajo un nuevo arreglo. Tal como en la indexación hacemos uso de paréntesis cuadrados ([]) indicando el índice del elemento inicial a recuperar seguido del operador ($:$) para finalizar con el índice del elemento final (el cual no se incluye). Por ejemplo para arreglos unidimensionales:

```
vector[:]  #Devuelve el vector completo. Incluyendo todos sus elementos.
vector[2:5] #Devuelve los elementos desde el segundo índice hasta el cuarto índice (es decir, desde la tercera posición hasta la quinta posición).
vector[:5] #Devuelve los elementos desde el primer índice hasta el cuarto índice (es decir, hasta la quinta posición).
vector[2:] #Devuelve los elementos a partir del segundo índice hasta el final del arreglo (es decir, desde la tercera posición).
```
Si se requiere, se puede agregar luego del índice del elemento final nuevamente el operador ($:$) para indicar el paso con el que se deben recorrer los índices. Por ejemplo:

```
vector[::2] #Devuelve los elementos desde el inicio del arreglo hasta el final, saltando el índice en pasos de 2.
vector[2:5:2] #Devuelve los elementos desde el segundo índice hasta el cuarto índice saltando el índice en pasos de 2.
```

Para arreglos bidimensionales (matrices) mantenemos la sintaxis anterior para indicar las secciones que se quieren recuperar tanto de filas como de columnas. Por ejemplo:

```
matriz[:,:]  #Devuelve la matriz completa. Incluyendo todos los elementos tanto de filas como de columnas
matriz[2:5,:] #Devuelve los elementos desde el tercera fila (índice 2) hasta la quinta fila (índice 4), incluyendo todas las columnas. 
matriz[:,:5] #Devuelve los elementos para todas las filas desde la primera columna hasta la quinta columna (índice 4).
matriz[2:,:] #Devuelve los elementos a partir de la tercera fila (índice 2) incluyendo todas las columnas.
matriz[::2,::3] #Devuelve las filas de la primera a la última con pasos de 2 posiciones y de la primera a la última columna con pasos de 3 posiciones.
```


**3.2. Ejercicios**

1. Escriba una función que reciba como argumento una matriz de NXN y retorne todos los elementos de la diagonal principal en un array de NumPy.

In [ ]:
# Complete la implementación
def diagonal_elements():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 3.2
matrix_example = np.array([
    [1,3,4],
    [0,2,5],
    [7,8,3]
])
diagonal_elements(matrix_example)

2. Escriba una función que reciba como argumentos una matriz de NxN y un número de fila y retorne la multiplicación de todos los elementos de dicha fila.

In [ ]:
# Complete la implementación
def row_product():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 3.2
matrix_example = np.array([
    [1,3,4],
    [0,2,5],
    [7,8,3]
])
print(row_product(matrix_example,3))

3. Escriba una función que reciba como argumentos una matriz de NxN y un número de columna y retorne la suma de todos los elementos de dicha columna.

In [ ]:
# Complete la implementación
def column_sum():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 3.2
matrix_example = np.array([
    [1,2,4],
    [7,3,1],
    [0,8,4]
])
print(column_sum(matrix_example,1))


4. Escriba una función que reciba como argumento una matriz y retorne su transpuesta como un arreglo de Numpy.

In [ ]:
# Complete la implementación
def transpose_matrix():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 3.2
matrix_example = np.array([
    [1,3,4],
    [0,2,5],
    [7,8,3],
    [2,78,9]
])
print(transpose_matrix(matrix_example))

**3.3. Tipos especiales de matrices en NumPy**

Numpy permite crear matrices especiales utilizando como argumento su tamaño (el método *shape*). Algunas matrices pueden ser:

- **Matriz donde todos sus elementos son 0:** Esta matriz puede ser creada utilizando la función *np.zeros()* donde como argumento *shape* se debe indicar el tamaño de la matriz.

- **Matriz donde todos sus elementos son 1:** Esta matriz puede ser creada utilizando la función *np.ones()* donde como argumento *shape* se debe indicar el tamaño de la matriz.

- **Matriz identidad:** Esta matriz puede ser creada utilizando la función *np.identity* que toma por argumento el número de filas ó de columnas, en cualquier caso genera una matriz cuadrada.

**Nota:** Hay que tener en cuenta que si se pasa como argumento un número entero positivo (y no la tupla que describe el tamaño de la matriz) a las funciones *np.ones()* y *np.zeros()*, estas generan un vector tomando dicho entero como el número total de elementos. 

**3.4. Ejercicios**

1. Genere un vector de 15 elementos donde todos sus elementos son el número 1 e imprima su tamaño.



2. Genere una matriz de 3 filas por 6 columnas donde todos sus elementos sean el número 0.



3. Genere una matriz de 8x8 donde todos los elementos de la diagonal principal son el número 1 y los demás son el número 0.



4. Escriba una función que reciba como argumento una matriz y retorne el promedio por filas de sus elementos en un arreglo de Numpy.

    **Hint:** ¿Que función tiene el parámetro axis dentro de la función np.mean()?

In [ ]:
# Complete la implementación
def average_row():
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 3.4
matrix_example = np.array([
    [3,5,4],
    [8,2,5],
    [7,8,3]
])
print(average_row(matrix_example))

5. Escriba una función que reciba como argumento una matriz y retorne el promedio por columnas de sus elementos en un arreglo de Numpy.

In [ ]:
def average_column(matrix:np.ndarray):
    pass

In [ ]:
# Ejemplo de prueba Ejercicio 3.4
matrix_example = np.array([
    [3,8,7],
    [5,2,8],
    [4,5,3]
])
print(average_column(matrix_example))

**3.4. Propiedades y operaciones matriciales con Numpy**

NumPy permite realizar distintas operaciones con matrices, entre las principales se encuentran:

```
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
```
- **Suma de matrices**: La suma de matrices elemento a elemento se realiza sumando las dos matrices como dos variables estandar.
```
c = a + b
[[ 6  8]
 [10 12]]
```
- **Resta de matrices**: La resta de matrices elemento a elemento se realiza restando las dos matrices como dos variables estandar.
```
c = a - b
[[-4 -4]
 [-4 -4]]
```
- **División de matrices**: La división de matrices elemento a elemento se realiza dividiendo las dos matrices como dos variables estandar (esto también incluye la división entera y la operación módulo).
```
c = a / b
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
```

- **Multiplicación de matrices (elemento a elemento)**: La multiplicación de matrices elemento a elemento se realiza multiplicando las dos matrices como dos variables estandar. *Este tipo de producto se conoce en matemáticas como Producto Hadamard.*
```
c = a * b
[[ 5 12]
 [21 32]]
```

- **Producto matricial**: El producto matricial se puede realizar de dos formas: utilizando la función *np.matmul()* o el símbolo '@' como operador. Bajo esta última implementación Numpy se ajusta automáticamente a los distintos tipos de producto que se dan a lugar entre vectores y matrices: 

- Si los dos objetos son vectores, se hace un producto punto al usar el operador '@'. Es equivalente usar la función *numpy.dot()*.
- Si los dos objetos son matrices, y satisfacen la relación necesaria entre filas y columnas de esta operación, se hace un producto matricial al usar el operador '@'. Es equivalente a usar la función *numpy.matmul()*.

En la versión reciente de Numpy, se ha extendido el uso de np.dot() y np.matmul() de modo que ahora es completamente equivalente usar cualquiera de las tres aproximaciones: '@', *numpy.dot()*. ó *numpy.matmul()*, y Numpy realiza el producto que tenga sentido de acuerdo a la naturaleza de los objetos que se operan. No obstante, Numpy recomienda usar el operador '@' sobre las otras funciones.
```
c = a @ b
[[19 22]
 [43 50]]
c = np.dot(a,b)
[[19 22]
 [43 50]]
```






**4.1. Ejercicios**

Para las siguientes parejas de matrices determine:

- Suma de las matrices elemento a elemento.

- Resta de las matrices elemento a elemento.

- División de las matrices elemento a elemento.

- Multiplicación de las matrices elemento a elemento.

- Producto matricial.

**Pareja 1:**

\begin{align}
 \begin{pmatrix}
 10 & 2 & 1 & \\
 24 & 1 & 2 & \\
 2 & 3 & 2 & \\
\end{pmatrix}  
 \begin{pmatrix}
 3 & 7 & 8 & \\
 2 & 1 & 3 & \\
 7 & 9 & 8 & \\
\end{pmatrix}
\end{align}


In [ ]:
#Suma de las matrices

In [ ]:
#Resta de las matrices

In [ ]:
#División de las matrices

In [ ]:
#Multiplicación de las matrices

In [ ]:
#Producto matricial


**Pareja 2:**

\begin{align}
 \begin{pmatrix}
 9 & 4 & 7 & \\
 4 & 6 & 2 & \\
 2 & 8 & 5 & \\
\end{pmatrix}
 \begin{pmatrix}
 1 & 2 & 4 & \\
 6 & 7 & 5 & \\
 16 & 14 & 7 & \\
\end{pmatrix}
\end{align}

In [ ]:
#Suma de las matrices

In [ ]:
#Resta de las matrices

In [ ]:
#División de las matrices

In [ ]:
#Multiplicación de las matrices

In [ ]:
#Producto matricial

**3.5. Operaciones de álgebra lineal**

Numpy permite realizar ciertas operaciones de álgebra lineal haciendo uso de su paquete *linalg*, veamos algunas de las principales:

- **np.linalg.det:** Calcula el determinante de un arreglo que debe ser MxM.

- **np.linalg.inv:** Calcula la inversa de un arreglo que debe ser MxM.

- **np.linalg.eig:** Calcula los autovalores y autovectores de un arreglo que debe ser
MxM y los retorna en la forma (W,v) donde W es un arreglo que contiene los autovalores y v un arreglo que contiene los autovectores asociados en el orden correspondiente.

**5.1. Ejercicios**

1. Para cada una de las siguientes matrices:

    a. Determine la dimensión del arreglo.

    b. Determine el tamaño (filas y columnas) de la matriz.

    c. Calcule el determinante de la matriz.

    d. Calcule la inversa de la matriz.      

    e. Calcule los valores y vectores propios, e imprímalos en pantalla de la siguiente manera:

  Autovalor 1: valor, Autovector 1: $[1,2...]$
  Autovalor 2: valor, Autovector 2: $[1,2...]$
  ...
  Autovalor n: valor, Autovector n: $[1,2...]$

Matriz 1

\begin{align}
 \begin{pmatrix}
 1 & 8 & 2 \\
 3 & 4 & 5 \\
 5 & 1 & 10 \\
\end{pmatrix}
 \end{align}


Matriz 2

\begin{align}
 \begin{pmatrix}
 7 & 6 & 3 \\
 2 & 9 & 5 \\
 3 & 7 & 10 \\
\end{pmatrix}
 \end{align}


Matriz 3

\begin{align}
 \begin{pmatrix}
 10 & 8 & 1 \\
 6 & 2 & 7 \\
 8 & 9 & 4 \\
\end{pmatrix}
 \end{align}

**3.6. Arange vs linspace**

Otros dos métodos conocidos para la creación de arrays unidimensionales (vectores) son *np.arange* y *np.linspace*. Estos métodos son usados especialmente cuando se busca crear arrays que representen, por ejemplo, una secuencia temporal, como por ejemplo un array representando la variable del tiempo que va de 0 a 50 segundos con pasos de 1 segundo. 

La función *np.arange* utiliza tres parámetros: el número que define el límite inicial del arreglo, el número que define el límite final del arreglo (que no se incluye), y el paso que existe entre cada dato. Mínimo, Numpy exige que se llame la función con límite final del intervalo, en este caso toma por defecto el límite inicial como 0 y el paso entre los datos como 1. El siguiente ejemplo, genera un arreglo unidimensional de 51 números entre 0 y 51.

```
array = np.arange(0,51,1)
```

La función *np.linspace* utiliza principalmente tres parámetros:el número que define el límite inicial del arreglo, el número que define el límite final del arreglo (que sí se incluye), y el número de elementos que debe contener el arreglo (es decir, la cantidad de números entre el límite inicial y el límite final). Mínimo, Numpy exige que se llame la función con los límites inicial y final del intervalo, en este caso toma por defecto el número de datos como 50. El siguiente ejemplo, genera un arreglo unidimensional con los números de 0 hasta 50, en pasos de 1.

```
array = np.linspace(0,50,51)
```

La principal diferencia entre estos métodos se da en que *np.arange* no incluye el límite final y requiere que se defina el paso entre los datos, mientras *np.linspace* incluye el límite final y requiere que se especifique el número de datos que se quiere al interior del arreglo, Numpy de forma interna calcula el paso entre los datos necesario para que se cumplan las condiciones establecidas.

**Nota:** El parámetro que define el paso entre los datos en *np.arange* no debe ser necesariamente entero, puede pasarse un float (un número decimal) de paso.




**6.1. Ejercicios**

1. Defina un arreglo que con pasos de 0.25 avance de 10 hasta 20 (incluyendo ambos límites). Imprima su longitud.



2. Defina un arreglo que contenga 100 números entre 1 y 5 (incluyendo ambos límites).



3. Defina dos arreglos con los límites de su preferencia (deben ser los mismos para ambos arreglos) utilizando los dos métodos, de modo que ambos tengan los mismos elementos y el mismo número de datos (imprima la longitud de cada uno).